Repository fipl-hse/2023-2-level-labs, pull requests merged in 2023-11, with the labels that each got.

#118 [DOCS] All docs in RST
  .github/workflows/ci_pipeline.yml
  .gitignore
  README.rst
  conf.py
  config/spellcheck/.spellcheck.yaml
  config/spellcheck/.wordlist.txt
  config/spellcheck/.wordlist_en.txt
  config/stage_1_style_tests/.doc8
  config/stage_1_style_tests/.flake8
  config/stage_1_style_tests/.pydocstyle
  config/stage_1_style_tests/_stage_docstring_check.sh
  config/stage_1_style_tests/_stage_run_doc8.sh
  config/stage_1_style_tests/_stage_run_flake8.sh
  config/stage_1_style_tests/requirements_check.py
  config/website/__init__.py
  config/website/_stage_run_sphinx_build.sh
  config/website/api_generator/__init__.py
  config/website/api_generator/generate_api_docs.py
  config/website/test_sphinx_project/Makefile
  config/website/test_sphinx_project/__init__.py
  config/website/test_sphinx_project/bom.txt
  docs/images/fork_update/add_upstream.png
  docs/images/fork_update/copy_original_repo_url.png
  docs/images/fork_update/fetch_upstream.png
  docs/images/fork_update/merge_upstream.png
  docs/images/fork_update/pycharm_open_terminal.png
  docs/images/starting_guide/implemented_function.png
  docs/images/starting_guide/initial_function_state.png
  docs/images/tests/ci_report.png
  docs/images/tests/ci_tab.png
  docs/images/tests/pycharm_choose_pytest_template.jpg
  docs/images/tests/pycharm_control_tests_scope.jpg
  docs/images/tests/pycharm_create_configuration.jpg
  docs/images/tests/pycharm_fill_pytest_configuration.jpg
  docs/images/tests/pycharm_run_pytest.jpg
  docs/images/tests/pycharm_tests_report.png
  docs/public/FAQ.rst
  docs/public/actions_ru.rst
  docs/public/fork_update.rst
  docs/public/lectures_content_ru.rst
  docs/public/starting_guide_ru.md
  docs/public/starting_guide_ru.rst
  docs/public/tests.md
  docs/public/tests.rst
  index.rst
  lab_1_classify_by_unigrams/README.rst
  lab_1_classify_by_unigrams/lab_1_classify_by_unigrams.api.rst
  lab_2_tokenize_by_bpe/README.rst
  lab_2_tokenize_by_bpe/lab_2_tokenize_by_bpe.api.rst
  pyproject.toml
  requirements_qa.txt
Labels: documentation

#78 Laboratory work #2, Anastasia Logunova - 22FPL1
  lab_2_tokenize_by_bpe/main.py
  lab_2_tokenize_by_bpe/start.py
  lab_2_tokenize_by_bpe/target_score.txt
Labels: :1st_place_medal: TOP WORK

#150 [SYNC] [WW46] New lectures
  README.rst
  config/spellcheck/.wordlist_en.txt
  docs/public/lectures_content_ru.rst
  seminars/practice_7_tic_tac_toe.py
Labels: documentation

#153 [SEMINARS] Inheritance
  seminars/practice_8_inheritance.py
Labels: Seminar listing

#127 Laboratory work #3, Margarita Velmisova - 22FPL1
  lab_3_generate_by_ngrams/main.py
  lab_3_generate_by_ngrams/start.py
  lab_3_generate_by_ngrams/target_score.txt
Labels: Approved, :1st_place_medal: TOP WORK
